# Altyapi kurma (from dockerHub)

From node:20.09.0-alpine
# Calisma Alani 
WORKDIR / app

#Dosyalari Aktar : Copy local inImage

# COPY hello.js / app
# kisa yolu COPY . .  tum dosyalari alir wordirection app in icine atar 
 COPY . .


# After build (when image to container)

CMD node hello.js